# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    environment:
        CC_TEST_REPORTER_ID: 4cdcaaeb24289d25a78871c4ed16880414587df95e698efb88bb4db4379da007
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      # run tests!
      - run:
          command:  !
            ./cc-test-reporter before-build
            mvn integration-test
            ./cc-test-reporter after-build --coverage-input-type cobertura --exit-code $?

      # run sonar
      - run:
          command:  !
            mvn sonar:sonar \
              -Dsonar.organization=jonyfs-github \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=a13743a8ba1dd02c8d7a8283fdc34c975efb5336
